name: "Sanity Template Validator"
description: "Validates Sanity.io template repositories"
inputs:
  github_token:
    description: "GitHub token for API access"
    required: true
  repository:
    description: "Repository to validate (owner/repo)"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
