name: Test GitHub Action
on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Sanity Template with GitHub Action
        uses: sanity-io/template-validator@v2
        with:
          directory: "test/fixtures/test-template"
